import type { SidebarItem } from '~/shared/client/nav'

/** Additional components. Consumers sort them together with core components. */
export const additionalComponentNavItems: SidebarItem[] = [
  { text: 'Affix', link: '/components/affix' },
  { text: 'Anchor', link: '/components/anchor' },
  { text: 'Backtop', link: '/components/backtop' },
  { text: 'Breadcrumb', link: '/components/breadcrumb' },
  { text: 'Calendar', link: '/components/calendar' },
  { text: 'Carousel', link: '/components/carousel' },
  { text: 'Cascader', link: '/components/cascader' },
  { text: 'Chip', link: '/components/chip' },
  { text: 'Collapse', link: '/components/collapse' },
  { text: 'Color picker', link: '/components/color-picker' },
  { text: 'Context menu', link: '/components/context-menu' },
  { text: 'Control group', link: '/components/control-group' },
  { text: 'Countdown', link: '/components/countdown' },
  { text: 'Date panel', link: '/components/date-panel' },
  { text: 'Date range picker', link: '/components/date-range-picker' },
  { text: 'Divider', link: '/components/divider' },
  { text: 'Drawer', link: '/components/drawer' },
  { text: 'Empty', link: '/components/empty' },
  { text: 'Form', link: '/components/form' },
  { text: 'Form group', link: '/components/form-group' },
  { text: 'Icon picker', link: '/components/icon-picker' },
  { text: 'Image preview', link: '/components/image-preview' },
  { text: 'Images', link: '/components/images' },
  { text: 'Layout', link: '/components/layout' },
  { text: 'Link', link: '/components/link' },
  { text: 'List', link: '/components/list' },
  { text: 'Menu', link: '/components/menu' },
  { text: 'Notice bar', link: '/components/notice-bar' },
  { text: 'Password input', link: '/components/password-input' },
  { text: 'Print', link: '/components/print' },
  { text: 'Print page break', link: '/components/print-page-break' },
  { text: 'Progress', link: '/components/progress' },
  { text: 'Prompt', link: '/components/prompt' },
  { text: 'Pulldown', link: '/components/pulldown' },
  { text: 'Radio button', link: '/components/radio-button' },
  { text: 'Radio group', link: '/components/radio-group' },
  { text: 'Result', link: '/components/result' },
  { text: 'Segmented', link: '/components/segmented' },
  { text: 'Slider', link: '/components/slider' },
  { text: 'Spacer', link: '/components/spacer' },
  { text: 'Splitter', link: '/components/splitter' },
  { text: 'Steps', link: '/components/steps' },
  { text: 'Tabs', link: '/components/tabs' },
  { text: 'Tag', link: '/components/tag' },
  { text: 'Text', link: '/components/text' },
  { text: 'Text ellipsis', link: '/components/text-ellipsis' },
  { text: 'Textarea', link: '/components/textarea' },
  { text: 'Tree', link: '/components/tree' },
  { text: 'Tree select', link: '/components/tree-select' },
  { text: 'Upload', link: '/components/upload' },
  { text: 'Virtual list', link: '/components/virtual-list' },
  { text: 'Watermark', link: '/components/watermark' },
]
