import { additionalComponentNavItems } from './new-components'
import type { SidebarItem } from '~/shared/client/nav'

/** Chinese meanings used by the Chinese sidebar and component page headers. */
export const componentNamesZh: Record<string, string> = {
  Alert: '警告提示',
  Avatar: '头像',
  Badge: '徽标',
  Button: '按钮',
  Card: '卡片',
  Checkbox: '复选框',
  'Date picker': '日期选择器',
  Dialog: '对话框',
  Input: '输入框',
  Loading: '加载',
  Navbar: '导航栏',
  Notification: '通知',
  Pagination: '分页',
  Radio: '单选框',
  Rate: '评分',
  Scrollbar: '滚动条',
  Select: '选择器',
  Sidebar: '侧边栏',
  Switch: '开关',
  Table: '表格',
  'Time picker': '时间选择器',
  'Time select': '时间选择',
  Tooltip: '文字提示',
  Affix: '固钉',
  Anchor: '锚点',
  Backtop: '回到顶部',
  Breadcrumb: '面包屑',
  Calendar: '日历',
  Carousel: '轮播图',
  Cascader: '级联选择器',
  'Checkbox button': '复选按钮',
  Chip: '标签块',
  Collapse: '折叠面板',
  'Color picker': '颜色选择器',
  'Context menu': '右键菜单',
  'Control group': '连续控件',
  Countdown: '倒计时',
  'Date panel': '日期面板',
  'Date range picker': '日期范围选择器',
  Divider: '分割线',
  Drawer: '抽屉',
  Empty: '空状态',
  Form: '表单',
  'Form group': '表单分组',
  'Icon picker': '图标选择器',
  'Image preview': '图片预览',
  Images: '图片',
  Layout: '布局',
  Link: '链接',
  List: '列表',
  Menu: '菜单',
  'Notice bar': '公告栏',
  'Password input': '密码输入框',
  Print: '打印',
  'Print page break': '打印分页',
  Progress: '进度条',
  Prompt: '提示框',
  Pulldown: '下拉容器',
  'Radio button': '单选按钮',
  'Radio group': '单选组',
  Result: '结果',
  Segmented: '分段控制',
  Slider: '滑块',
  Spacer: '间隔',
  Splitter: '分割面板',
  Steps: '步骤条',
  Tabs: '标签页',
  Tag: '标签',
  Text: '文本',
  'Text ellipsis': '文本省略',
  Textarea: '文本域',
  Tree: '树形控件',
  'Tree select': '树形选择器',
  Upload: '上传',
  'Virtual list': '虚拟列表',
  Watermark: '水印',
}

/** Keep English component names and ordering; append only the Chinese meaning. */
export const additionalComponentNavItemsZh: SidebarItem[] =
  additionalComponentNavItems.map((item) => ({
    text: `${item.text}（${componentNamesZh[item.text] || item.text}）`,
    link: `/zh${item.link}`,
  }))
