import type { SidebarItem } from '~/shared/client/nav'

/** Migrated vuesax components — merged into Components menu with isNew badge. */
export const newComponentNavItems: SidebarItem[] = [
  { text: 'Backtop', link: '/components/backtop', isNew: true },
  { text: 'Anchor', link: '/components/anchor', isNew: true },
  { text: 'Spacer', link: '/components/spacer', isNew: true },
  { text: 'Divider', link: '/components/divider', isNew: true },
  { text: 'Drawer', link: '/components/drawer', isNew: true },
  { text: 'Empty', link: '/components/empty', isNew: true },
  { text: 'Form', link: '/components/form', isNew: true },
  { text: 'Progress', link: '/components/progress', isNew: true },
  { text: 'Chip', link: '/components/chip', isNew: true },
  { text: 'Calendar', link: '/components/calendar', isNew: true },
  { text: 'Carousel', link: '/components/carousel', isNew: true },
  { text: 'Cascader', link: '/components/cascader', isNew: true },
  { text: 'Breadcrumb', link: '/components/breadcrumb', isNew: true },
  { text: 'Color picker', link: '/components/color-picker', isNew: true },
  { text: 'Context menu', link: '/components/context-menu', isNew: true },
  { text: 'Textarea', link: '/components/textarea', isNew: true },
  { text: 'Collapse', link: '/components/collapse', isNew: true },
  { text: 'Countdown', link: '/components/countdown', isNew: true },
  { text: 'List', link: '/components/list', isNew: true },
  { text: 'Images', link: '/components/images', isNew: true },
  { text: 'Icon picker', link: '/components/icon-picker', isNew: true },
  { text: 'Image preview', link: '/components/image-preview', isNew: true },
  { text: 'Link', link: '/components/link', isNew: true },
  { text: 'Layout', link: '/components/layout', isNew: true },
  { text: 'Notice bar', link: '/components/notice-bar', isNew: true },
  { text: 'Segmented', link: '/components/segmented', isNew: true },
  { text: 'Prompt', link: '/components/prompt', isNew: true },
  { text: 'Pulldown', link: '/components/pulldown', isNew: true },
  { text: 'Password input', link: '/components/password-input', isNew: true },
  { text: 'Result', link: '/components/result', isNew: true },
  { text: 'Radio button', link: '/components/radio-button', isNew: true },
  { text: 'Tabs', link: '/components/tabs', isNew: true },
  { text: 'Tag', link: '/components/tag', isNew: true },
  { text: 'Text', link: '/components/text', isNew: true },
  { text: 'Text ellipsis', link: '/components/text-ellipsis', isNew: true },
  { text: 'Tree', link: '/components/tree', isNew: true },
  { text: 'Tree select', link: '/components/tree-select', isNew: true },
  { text: 'Slider', link: '/components/slider', isNew: true },
  { text: 'Splitter', link: '/components/splitter', isNew: true },
  { text: 'Steps', link: '/components/steps', isNew: true },
  { text: 'Upload', link: '/components/upload', isNew: true },
  { text: 'Virtual list', link: '/components/virtual-list', isNew: true },
  { text: 'Watermark', link: '/components/watermark', isNew: true },
]
