import * as baseIcons from '@vuesax-alpha/icons-vue'
import { extraIcons } from './extra-icons'
import type { Component } from 'vue'

export * from '@vuesax-alpha/icons-vue'
export { extraIcons } from './extra-icons'

export { default as Share } from './components/share.vue'
export { default as ShareBold } from './components/share-bold.vue'
export { default as Link } from './components/link.vue'
export { default as LinkBold } from './components/link-bold.vue'
export { default as Copy } from './components/copy.vue'
export { default as CopyBold } from './components/copy-bold.vue'
export { default as Calendar } from './components/calendar.vue'
export { default as CalendarBold } from './components/calendar-bold.vue'
export { default as Clock } from './components/clock.vue'
export { default as ClockBold } from './components/clock-bold.vue'
export { default as Refresh } from './components/refresh.vue'
export { default as RefreshBold } from './components/refresh-bold.vue'
export { default as Save } from './components/save.vue'
export { default as SaveBold } from './components/save-bold.vue'
export { default as Print } from './components/print.vue'
export { default as PrintBold } from './components/print-bold.vue'
export { default as Sort } from './components/sort.vue'
export { default as SortBold } from './components/sort-bold.vue'
export { default as Bookmark } from './components/bookmark.vue'
export { default as BookmarkBold } from './components/bookmark-bold.vue'
export { default as Chart } from './components/chart.vue'
export { default as ChartBold } from './components/chart-bold.vue'
export { default as Cart } from './components/cart.vue'
export { default as CartBold } from './components/cart-bold.vue'
export { default as Wallet } from './components/wallet.vue'
export { default as WalletBold } from './components/wallet-bold.vue'
export { default as Wifi } from './components/wifi.vue'
export { default as WifiBold } from './components/wifi-bold.vue'
export { default as MapPin } from './components/map-pin.vue'
export { default as MapPinBold } from './components/map-pin-bold.vue'
export { default as Paperclip } from './components/paperclip.vue'
export { default as PaperclipBold } from './components/paperclip-bold.vue'
export { default as Fullscreen } from './components/fullscreen.vue'
export { default as FullscreenBold } from './components/fullscreen-bold.vue'
export { default as Power } from './components/power.vue'
export { default as PowerBold } from './components/power-bold.vue'
export { default as Chat } from './components/chat.vue'
export { default as ChatBold } from './components/chat-bold.vue'
export { default as Comment } from './components/comment.vue'
export { default as CommentBold } from './components/comment-bold.vue'
export { default as Flag } from './components/flag.vue'
export { default as FlagBold } from './components/flag-bold.vue'
export { default as Block } from './components/block.vue'
export { default as BlockBold } from './components/block-bold.vue'
export { default as InfoCircle } from './components/info-circle.vue'
export { default as InfoCircleBold } from './components/info-circle-bold.vue'
export { default as Warning } from './components/warning.vue'
export { default as WarningBold } from './components/warning-bold.vue'
export { default as HelpCircle } from './components/help-circle.vue'
export { default as HelpCircleBold } from './components/help-circle-bold.vue'
export { default as Pencil } from './components/pencil.vue'
export { default as PencilBold } from './components/pencil-bold.vue'
export { default as Mail } from './components/mail.vue'
export { default as MailBold } from './components/mail-bold.vue'
export { default as Sun } from './components/sun.vue'
export { default as SunBold } from './components/sun-bold.vue'
export { default as Moon } from './components/moon.vue'
export { default as MoonBold } from './components/moon-bold.vue'
export { default as Bluetooth } from './components/bluetooth.vue'
export { default as BluetoothBold } from './components/bluetooth-bold.vue'
export { default as Card } from './components/card.vue'
export { default as CardBold } from './components/card-bold.vue'
export { default as Shop } from './components/shop.vue'
export { default as ShopBold } from './components/shop-bold.vue'
export { default as ExternalLink } from './components/external-link.vue'
export { default as ExternalLinkBold } from './components/external-link-bold.vue'
export { default as File } from './components/file.vue'
export { default as FileBold } from './components/file-bold.vue'
export { default as Filter } from './components/filter.vue'
export { default as FilterBold } from './components/filter-bold.vue'
export { default as Verified } from './components/verified.vue'
export { default as VerifiedBold } from './components/verified-bold.vue'
export { default as Cloud } from './components/cloud.vue'
export { default as CloudBold } from './components/cloud-bold.vue'
export { default as Attach } from './components/attach.vue'
export { default as AttachBold } from './components/attach-bold.vue'
export { default as Expand } from './components/expand.vue'
export { default as ExpandBold } from './components/expand-bold.vue'
export { default as Photo } from './components/photo.vue'
export { default as PhotoBold } from './components/photo-bold.vue'
export { default as Phone } from './components/phone.vue'
export { default as PhoneBold } from './components/phone-bold.vue'
export { default as Delete } from './components/delete.vue'
export { default as DeleteBold } from './components/delete-bold.vue'

export const saxIcons = {
  ...(baseIcons as Record<string, Component>),
  ...extraIcons,
} as Record<string, Component>

export default saxIcons

export {
  buildIconCatalog,
  filterIconCatalog,
  iconNameToKebab,
} from './registry'
