import '@vuesax-alpha/components/base/style'
import '@vuesax-alpha/components/button/style'
import '@vuesax-alpha/components/checkbox/style'
import '@vuesax-alpha/components/radio/style'
import '@vuesax-alpha/components/icon/style'
import '@vuesax-alpha/components/popper/style'
import '@vuesax-alpha/components/pagination/style'
import '@vuesax-alpha/components/select/style'
import '@vuesax-alpha/components/virtual-list/style'

import '@vuesax-alpha/theme-chalk/src/table.scss'
