import type { SaxIconData } from './icon'

// Generated by scripts/generate-builtin-icon-fallbacks.ts. Do not edit manually.
export const builtinCarbonIcons: Record<string, SaxIconData> = {
  add: {
    body: '<path fill="currentColor" d="M17 15V8h-2v7H8v2h7v7h2v-7h7v-2z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'arrow-down': {
    body: '<path fill="currentColor" d="M24.59 16.59L17 24.17V4h-2v20.17l-7.59-7.58L6 18l10 10l10-10z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'arrow-left': {
    body: '<path fill="currentColor" d="m14 26l1.41-1.41L7.83 17H28v-2H7.83l7.58-7.59L14 6L4 16z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'arrow-right': {
    body: '<path fill="currentColor" d="m18 6l-1.43 1.393L24.15 15H4v2h20.15l-7.58 7.573L18 26l10-10z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'arrow-up': {
    body: '<path fill="currentColor" d="M16 4L6 14l1.41 1.41L15 7.83V28h2V7.83l7.59 7.58L26 14z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  calendar: {
    body: '<path fill="currentColor" d="M26 4h-4V2h-2v2h-8V2h-2v2H6c-1.1 0-2 .9-2 2v20c0 1.1.9 2 2 2h20c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2m0 22H6V12h20zm0-16H6V6h4v2h2V6h8v2h2V6h4z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'caret-down': {
    body: '<path fill="currentColor" d="m24 12l-8 10l-8-10z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'caret-up': {
    body: '<path fill="currentColor" d="m8 20l8-10l8 10z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  chat: {
    body: '<path fill="currentColor" d="M17.74 30L16 29l4-7h6a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h9v2H6a4 4 0 0 1-4-4V8a4 4 0 0 1 4-4h20a4 4 0 0 1 4 4v12a4 4 0 0 1-4 4h-4.84Z"/><path fill="currentColor" d="M8 10h16v2H8zm0 6h10v2H8z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  checkmark: {
    body: '<path fill="currentColor" d="m13 24l-9-9l1.414-1.414L13 21.171L26.586 7.586L28 9z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'checkmark-filled': {
    body: '<path fill="currentColor" d="M16 2a14 14 0 1 0 14 14A14 14 0 0 0 16 2m-2 19.59l-5-5L10.59 15L14 18.41L21.41 11l1.596 1.586Z"/><path fill="none" d="m14 21.591l-5-5L10.591 15L14 18.409L21.41 11l1.595 1.585z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'chevron-down': {
    body: '<path fill="currentColor" d="M16 22L6 12l1.4-1.4l8.6 8.6l8.6-8.6L26 12z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'chevron-left': {
    body: '<path fill="currentColor" d="M10 16L20 6l1.4 1.4l-8.6 8.6l8.6 8.6L20 26z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'chevron-right': {
    body: '<path fill="currentColor" d="M22 16L12 26l-1.4-1.4l8.6-8.6l-8.6-8.6L12 6z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'chevron-up': {
    body: '<path fill="currentColor" d="m16 10l10 10l-1.4 1.4l-8.6-8.6l-8.6 8.6L6 20z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  close: {
    body: '<path fill="currentColor" d="M17.414 16L24 9.414L22.586 8L16 14.586L9.414 8L8 9.414L14.586 16L8 22.586L9.414 24L16 17.414L22.586 24L24 22.586z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'cloud-upload': {
    body: '<path fill="currentColor" d="m11 18l1.41 1.41L15 16.83V29h2V16.83l2.59 2.58L21 18l-5-5z"/><path fill="currentColor" d="M23.5 22H23v-2h.5a4.5 4.5 0 0 0 .36-9H23l-.1-.82a7 7 0 0 0-13.88 0L9 11h-.86a4.5 4.5 0 0 0 .36 9H9v2h-.5A6.5 6.5 0 0 1 7.2 9.14a9 9 0 0 1 17.6 0A6.5 6.5 0 0 1 23.5 22"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  code: {
    body: '<path fill="currentColor" d="m31 16l-7 7l-1.41-1.41L28.17 16l-5.58-5.59L24 9zM1 16l7-7l1.41 1.41L3.83 16l5.58 5.59L8 23zm11.42 9.484L17.64 6l1.932.517L14.352 26z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'color-picker': {
    body: '<path fill="currentColor" d="M2 27h3v3H2zM29.71 7.3v-.01l-5-5a1 1 0 0 0-1.41 0L20 5.59l-1.29-1.3l-1.42 1.42L18.59 7L8.29 17.29A1 1 0 0 0 8 18v1.59l-2.71 2.7a1 1 0 0 0 0 1.41l3 3a1 1 0 0 0 1.41 0l2.71-2.7H14a1 1 0 0 0 .71-.29L25 13.41l1.29 1.3l1.42-1.42l-1.3-1.29l3.3-3.29a1 1 0 0 0 0-1.41m-10.117 8.697h-7.18L20 8.41L23.59 12zM25 10.59L21.41 7L24 4.41L27.59 8z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  copy: {
    body: '<path fill="currentColor" d="M28 10v18H10V10zm0-2H10a2 2 0 0 0-2 2v18a2 2 0 0 0 2 2h18a2 2 0 0 0 2-2V10a2 2 0 0 0-2-2"/><path fill="currentColor" d="M4 18H2V4a2 2 0 0 1 2-2h14v2H4Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  document: {
    body: '<path fill="currentColor" d="m25.7 9.3l-7-7c-.2-.2-.4-.3-.7-.3H8c-1.1 0-2 .9-2 2v24c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V10c0-.3-.1-.5-.3-.7M18 4.4l5.6 5.6H18zM24 28H8V4h8v6c0 1.1.9 2 2 2h6z"/><path fill="currentColor" d="M10 22h12v2H10zm0-6h12v2H10z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'double-chevron-left': {
    body: '<path fill="currentColor" d="M24.485 25.9L14.586 16l9.9-9.9l1.413 1.415L17.415 16l8.485 8.486zm-8.5 0L6.086 16l9.9-9.9l1.413 1.415L8.915 16l8.486 8.486z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'double-chevron-right': {
    body: '<path fill="currentColor" d="M16.015 25.9L14.6 24.484L23.086 16L14.6 7.515L16.015 6.1l9.9 9.899zm-8.5 0L6.1 24.484L14.586 16L6.1 7.515L7.515 6.1l9.9 9.899z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  download: {
    body: '<path fill="currentColor" d="M26 24v4H6v-4H4v4a2 2 0 0 0 2 2h20a2 2 0 0 0 2-2v-4Zm0-10l-1.41-1.41L17 20.17V2h-2v18.17l-7.59-7.58L6 14l10 10z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  draggable: {
    body: '<path fill="currentColor" d="M10 6h4v4h-4zm8 0h4v4h-4zm-8 8h4v4h-4zm8 0h4v4h-4zm-8 8h4v4h-4zm8 0h4v4h-4z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  edit: {
    body: '<path fill="currentColor" d="M2 26h28v2H2zM25.4 9c.8-.8.8-2 0-2.8l-3.6-3.6c-.8-.8-2-.8-2.8 0l-15 15V24h6.4zm-5-5L24 7.6l-3 3L17.4 7zM6 22v-3.6l10-10l3.6 3.6l-10 10z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'expand-all': {
    body: '<path fill="currentColor" d="M12 10h14a2.003 2.003 0 0 0 2-2V4a2.003 2.003 0 0 0-2-2H12a2.003 2.003 0 0 0-2 2v1H6V2H4v23a2.003 2.003 0 0 0 2 2h4v1a2.003 2.003 0 0 0 2 2h14a2.003 2.003 0 0 0 2-2v-4a2.003 2.003 0 0 0-2-2H12a2.003 2.003 0 0 0-2 2v1H6v-8h4v1a2.003 2.003 0 0 0 2 2h14a2.003 2.003 0 0 0 2-2v-4a2.003 2.003 0 0 0-2-2H12a2.003 2.003 0 0 0-2 2v1H6V7h4v1a2.003 2.003 0 0 0 2 2m0-6h14l.001 4H12Zm0 20h14l.001 4H12Zm0-10h14l.001 4H12Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  filter: {
    body: '<path fill="currentColor" d="M18 28h-4a2 2 0 0 1-2-2v-7.59L4.59 11A2 2 0 0 1 4 9.59V6a2 2 0 0 1 2-2h20a2 2 0 0 1 2 2v3.59a2 2 0 0 1-.59 1.41L20 18.41V26a2 2 0 0 1-2 2M6 6v3.59l8 8V26h4v-8.41l8-8V6Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  help: {
    body: '<path fill="currentColor" d="M16 2a14 14 0 1 0 14 14A14 14 0 0 0 16 2m0 26a12 12 0 1 1 12-12a12 12 0 0 1-12 12"/><circle cx="16" cy="23.5" r="1.5" fill="currentColor"/><path fill="currentColor" d="M17 8h-1.5a4.49 4.49 0 0 0-4.5 4.5v.5h2v-.5a2.5 2.5 0 0 1 2.5-2.5H17a2.5 2.5 0 0 1 0 5h-2v4.5h2V17a4.5 4.5 0 0 0 0-9"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  image: {
    body: '<path fill="currentColor" d="M19 14a3 3 0 1 0-3-3a3 3 0 0 0 3 3m0-4a1 1 0 1 1-1 1a1 1 0 0 1 1-1"/><path fill="currentColor" d="M26 4H6a2 2 0 0 0-2 2v20a2 2 0 0 0 2 2h20a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2m0 22H6v-6l5-5l5.59 5.59a2 2 0 0 0 2.82 0L21 19l5 5Zm0-4.83l-3.59-3.59a2 2 0 0 0-2.82 0L18 19.17l-5.59-5.59a2 2 0 0 0-2.82 0L6 17.17V6h20Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  locked: {
    body: '<path fill="currentColor" d="M24 14h-2V8a6 6 0 0 0-12 0v6H8a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V16a2 2 0 0 0-2-2M12 8a4 4 0 0 1 8 0v6h-8Zm12 20H8V16h16Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'overflow-menu-horizontal': {
    body: '<circle cx="8" cy="16" r="2" fill="currentColor"/><circle cx="16" cy="16" r="2" fill="currentColor"/><circle cx="24" cy="16" r="2" fill="currentColor"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'overflow-menu-vertical': {
    body: '<circle cx="16" cy="8" r="2" fill="currentColor"/><circle cx="16" cy="16" r="2" fill="currentColor"/><circle cx="16" cy="24" r="2" fill="currentColor"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  pin: {
    body: '<path fill="currentColor" d="M28.59 13.31L30 11.9L20 2l-1.31 1.42l1.18 1.18l-11.49 9.72l-1.72-1.71L5.25 14l5.66 5.68L2 28.58L3.41 30l8.91-8.91L18 26.75l1.39-1.42l-1.71-1.71l9.72-11.49ZM16.26 22.2L9.8 15.74L21.29 6L26 10.71Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'pin-filled': {
    body: '<path fill="currentColor" d="M28.586 13.314L30 11.9L20 2l-1.314 1.415l1.186 1.186L8.38 14.322l-1.716-1.715L5.25 14l5.657 5.677L2 28.583L3.41 30l8.911-8.909L18 26.748l1.393-1.414l-1.716-1.716l9.724-11.49Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'radio-button': {
    body: '<path fill="currentColor" d="M16 2a14 14 0 1 0 14 14A14 14 0 0 0 16 2m0 26a12 12 0 1 1 12-12a12 12 0 0 1-12 12"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'recently-viewed': {
    body: '<path fill="currentColor" d="M20.59 22L15 16.41V7h2v8.58l5 5.01z"/><path fill="currentColor" d="M16 2A13.94 13.94 0 0 0 6 6.23V2H4v8h8V8H7.08A12 12 0 1 1 4 16H2A14 14 0 1 0 16 2"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  renew: {
    body: '<path fill="currentColor" d="M12 10H6.78A11 11 0 0 1 27 16h2A13 13 0 0 0 6 7.68V4H4v8h8Zm8 12h5.22A11 11 0 0 1 5 16H3a13 13 0 0 0 23 8.32V28h2v-8h-8Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  reset: {
    body: '<path fill="currentColor" d="M18 28A12 12 0 1 0 6 16v6.2l-3.6-3.6L1 20l6 6l6-6l-1.4-1.4L8 22.2V16a10 10 0 1 1 10 10Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  rotate: {
    body: '<path fill="currentColor" d="m17.91 26.82l.35 2a12.9 12.9 0 0 0 4.24-1.54l-1-1.73a10.9 10.9 0 0 1-3.59 1.27m6.51-3.75L26 24.35a13 13 0 0 0 2.24-3.91l-1.87-.68a11 11 0 0 1-1.95 3.31M9.5 27.25a12.9 12.9 0 0 0 4.24 1.54l.35-2a10.9 10.9 0 0 1-3.59-1.3Zm-3.83-7.49l-1.87.68A13 13 0 0 0 6 24.35l.32-.26l1.22-1a11 11 0 0 1-1.91-3.31ZM29 16a12.9 12.9 0 0 0-.8-4.44l-1.87.68A11.2 11.2 0 0 1 27 16Zm-3-8.35a13 13 0 0 0-20 0V4H4v8h8v-2H6.81a11 11 0 0 1 17.61-1.07Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  search: {
    body: '<path fill="currentColor" d="m29 27.586l-7.552-7.552a11.018 11.018 0 1 0-1.414 1.414L27.586 29ZM4 13a9 9 0 1 1 9 9a9.01 9.01 0 0 1-9-9"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'search-locate': {
    body: '<path fill="currentColor" d="m30 28.586l-4.688-4.688a8.028 8.028 0 1 0-1.415 1.414L28.586 30ZM19 25a6 6 0 1 1 6-6a6.007 6.007 0 0 1-6 6M2 12h8v2H2zM2 2h16v2H2zm0 5h16v2H2z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  settings: {
    body: '<path fill="currentColor" d="M27 16.76v-1.53l1.92-1.68A2 2 0 0 0 29.3 11l-2.36-4a2 2 0 0 0-1.73-1a2 2 0 0 0-.64.1l-2.43.82a11 11 0 0 0-1.31-.75l-.51-2.52a2 2 0 0 0-2-1.61h-4.68a2 2 0 0 0-2 1.61l-.51 2.52a11.5 11.5 0 0 0-1.32.75l-2.38-.86A2 2 0 0 0 6.79 6a2 2 0 0 0-1.73 1L2.7 11a2 2 0 0 0 .41 2.51L5 15.24v1.53l-1.89 1.68A2 2 0 0 0 2.7 21l2.36 4a2 2 0 0 0 1.73 1a2 2 0 0 0 .64-.1l2.43-.82a11 11 0 0 0 1.31.75l.51 2.52a2 2 0 0 0 2 1.61h4.72a2 2 0 0 0 2-1.61l.51-2.52a11.5 11.5 0 0 0 1.32-.75l2.42.82a2 2 0 0 0 .64.1a2 2 0 0 0 1.73-1l2.28-4a2 2 0 0 0-.41-2.51ZM25.21 24l-3.43-1.16a8.9 8.9 0 0 1-2.71 1.57L18.36 28h-4.72l-.71-3.55a9.4 9.4 0 0 1-2.7-1.57L6.79 24l-2.36-4l2.72-2.4a8.9 8.9 0 0 1 0-3.13L4.43 12l2.36-4l3.43 1.16a8.9 8.9 0 0 1 2.71-1.57L13.64 4h4.72l.71 3.55a9.4 9.4 0 0 1 2.7 1.57L25.21 8l2.36 4l-2.72 2.4a8.9 8.9 0 0 1 0 3.13L27.57 20Z"/><path fill="currentColor" d="M16 22a6 6 0 1 1 6-6a5.94 5.94 0 0 1-6 6m0-10a3.91 3.91 0 0 0-4 4a3.91 3.91 0 0 0 4 4a3.91 3.91 0 0 0 4-4a3.91 3.91 0 0 0-4-4"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  stop: {
    body: '<path fill="currentColor" d="M24 8v16H8V8zm0-2H8a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  subtract: {
    body: '<path fill="currentColor" d="M8 15h16v2H8z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  task: {
    body: '<path fill="currentColor" d="m14 20.18l-3.59-3.59L9 18l5 5l9-9l-1.41-1.42z"/><path fill="currentColor" d="M25 5h-3V4a2 2 0 0 0-2-2h-8a2 2 0 0 0-2 2v1H7a2 2 0 0 0-2 2v21a2 2 0 0 0 2 2h18a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2M12 4h8v4h-8Zm13 24H7V7h3v3h12V7h3Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'task-complete': {
    body: '<path fill="currentColor" d="m22 27.18l-2.59-2.59L18 26l4 4l8-8l-1.41-1.41z"/><path fill="currentColor" d="M25 5h-3V4a2.006 2.006 0 0 0-2-2h-8a2.006 2.006 0 0 0-2 2v1H7a2.006 2.006 0 0 0-2 2v21a2.006 2.006 0 0 0 2 2h9v-2H7V7h3v3h12V7h3v11h2V7a2.006 2.006 0 0 0-2-2m-5 3h-8V4h8Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'text-bold': {
    body: '<path fill="currentColor" d="M18.25 25H9V7h8.5a5.25 5.25 0 0 1 4 8.65A5.25 5.25 0 0 1 18.25 25M12 22h6.23a2.25 2.25 0 1 0 0-4.5H12Zm0-7.5h5.5a2.25 2.25 0 1 0 0-4.5H12Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'text-italic': {
    body: '<path fill="currentColor" d="M25 9V7H12v2h5.14l-4.37 14H7v2h13v-2h-5.14l4.37-14z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'text-strikethrough': {
    body: '<path fill="currentColor" d="M28 15H17.956a40 40 0 0 0-1.338-.335c-2.808-.664-4.396-1.15-4.396-3.423a2.87 2.87 0 0 1 .787-2.145a4.8 4.8 0 0 1 3.013-1.09c2.83-.07 4.135.89 5.202 2.35l1.615-1.18a7.47 7.47 0 0 0-6.83-3.17a6.77 6.77 0 0 0-4.4 1.661a4.83 4.83 0 0 0-1.386 3.574A4.37 4.37 0 0 0 11.957 15H4v2h13.652c1.967.57 3.143 1.312 3.173 3.358a3.12 3.12 0 0 1-.862 2.393A5.82 5.82 0 0 1 16.243 24a6.63 6.63 0 0 1-5.145-2.691l-1.533 1.284A8.53 8.53 0 0 0 16.212 26h.1a7.67 7.67 0 0 0 5.048-1.819a5.08 5.08 0 0 0 1.465-3.853A4.95 4.95 0 0 0 21.675 17H28Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'text-underline': {
    body: '<path fill="currentColor" d="M4 26h24v2H4zm12-3a7 7 0 0 1-7-7V5h2v11a5 5 0 0 0 10 0V5h2v11a7 7 0 0 1-7 7"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'thumbs-down': {
    body: '<path fill="currentColor" d="M30 16V9a7.01 7.01 0 0 0-7-7H2v14h6.465l3.577 5.366l.846 5.917A2.01 2.01 0 0 0 14.868 29H17a3.003 3.003 0 0 0 3-3v-6h6a4.005 4.005 0 0 0 4-4M8 14H4V4h4Zm20 2a2.003 2.003 0 0 1-2 2h-8v8a1 1 0 0 1-1 1h-2.133l-.91-6.366L10 14.697V4h13a5.006 5.006 0 0 1 5 5Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'thumbs-up': {
    body: '<path fill="currentColor" d="M26 12h-6V6a3.003 3.003 0 0 0-3-3h-2.133a2.01 2.01 0 0 0-1.98 1.717l-.845 5.917L8.465 16H2v14h21a7.01 7.01 0 0 0 7-7v-7a4.005 4.005 0 0 0-4-4M8 28H4V18h4Zm20-5a5.006 5.006 0 0 1-5 5H10V17.303l3.958-5.937l.91-6.366H17a1 1 0 0 1 1 1v8h8a2.003 2.003 0 0 1 2 2Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  time: {
    body: '<path fill="currentColor" d="M16 30a14 14 0 1 1 14-14a14 14 0 0 1-14 14m0-26a12 12 0 1 0 12 12A12 12 0 0 0 16 4"/><path fill="currentColor" d="M20.59 22L15 16.41V7h2v8.58l5 5.01z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'trash-can': {
    body: '<path fill="currentColor" d="M12 12h2v12h-2zm6 0h2v12h-2z"/><path fill="currentColor" d="M4 6v2h2v20a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8h2V6Zm4 22V8h16v20Zm4-26h8v2h-8z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  view: {
    body: '<path fill="currentColor" d="M30.94 15.66A16.69 16.69 0 0 0 16 5A16.69 16.69 0 0 0 1.06 15.66a1 1 0 0 0 0 .68A16.69 16.69 0 0 0 16 27a16.69 16.69 0 0 0 14.94-10.66a1 1 0 0 0 0-.68M16 25c-5.3 0-10.9-3.93-12.93-9C5.1 10.93 10.7 7 16 7s10.9 3.93 12.93 9C26.9 21.07 21.3 25 16 25"/><path fill="currentColor" d="M16 10a6 6 0 1 0 6 6a6 6 0 0 0-6-6m0 10a4 4 0 1 1 4-4a4 4 0 0 1-4 4"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'view-off': {
    body: '<path fill="currentColor" d="m5.24 22.51l1.43-1.42A14.06 14.06 0 0 1 3.07 16C5.1 10.93 10.7 7 16 7a12.4 12.4 0 0 1 4 .72l1.55-1.56A14.7 14.7 0 0 0 16 5A16.69 16.69 0 0 0 1.06 15.66a1 1 0 0 0 0 .68a16 16 0 0 0 4.18 6.17"/><path fill="currentColor" d="M12 15.73a4 4 0 0 1 3.7-3.7l1.81-1.82a6 6 0 0 0-7.33 7.33Zm18.94-.07a16.4 16.4 0 0 0-5.74-7.44L30 3.41L28.59 2L2 28.59L3.41 30l5.1-5.1A15.3 15.3 0 0 0 16 27a16.69 16.69 0 0 0 14.94-10.66a1 1 0 0 0 0-.68M20 16a4 4 0 0 1-6 3.44L19.44 14a4 4 0 0 1 .56 2m-4 9a13.05 13.05 0 0 1-6-1.58l2.54-2.54a6 6 0 0 0 8.35-8.35l2.87-2.87A14.54 14.54 0 0 1 28.93 16C26.9 21.07 21.3 25 16 25"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  warning: {
    body: '<path fill="currentColor" d="M16 2a14 14 0 1 0 14 14A14 14 0 0 0 16 2m0 26a12 12 0 1 1 12-12a12 12 0 0 1-12 12"/><path fill="currentColor" d="M15 8h2v11h-2zm1 14a1.5 1.5 0 1 0 1.5 1.5A1.5 1.5 0 0 0 16 22"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'warning-alt': {
    body: '<path fill="currentColor" d="M16 23a1.5 1.5 0 1 0 1.5 1.5A1.5 1.5 0 0 0 16 23m-1-11h2v9h-2z"/><path fill="currentColor" d="M29 30H3a1 1 0 0 1-.887-1.461l13-25a1 1 0 0 1 1.774 0l13 25A1 1 0 0 1 29 30M4.65 28h22.7l.001-.003L16.002 6.17h-.004L4.648 27.997Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'warning-alt-filled': {
    body: '<path fill="none" d="M16 26a1.5 1.5 0 1 1 1.5-1.5A1.5 1.5 0 0 1 16 26m-1.125-5h2.25v-9h-2.25Z"/><path fill="currentColor" d="M16.002 6.171h-.004L4.648 27.997l.003.003h22.698l.002-.003ZM14.875 12h2.25v9h-2.25ZM16 26a1.5 1.5 0 1 1 1.5-1.5A1.5 1.5 0 0 1 16 26"/><path fill="currentColor" d="M29 30H3a1 1 0 0 1-.887-1.461l13-25a1 1 0 0 1 1.774 0l13 25A1 1 0 0 1 29 30M4.65 28h22.7l.001-.003L16.002 6.17h-.004L4.648 27.997Z"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'zoom-in': {
    body: '<path fill="currentColor" d="M18 12h-4V8h-2v4H8v2h4v4h2v-4h4z"/><path fill="currentColor" d="M21.448 20A10.86 10.86 0 0 0 24 13a11 11 0 1 0-11 11a10.86 10.86 0 0 0 7-2.552L27.586 29L29 27.586ZM13 22a9 9 0 1 1 9-9a9.01 9.01 0 0 1-9 9"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
  'zoom-out': {
    body: '<path fill="currentColor" d="M8 12h10v2H8z"/><path fill="currentColor" d="M21.448 20A10.86 10.86 0 0 0 24 13a11 11 0 1 0-11 11a10.86 10.86 0 0 0 7-2.552L27.586 29L29 27.586ZM13 22a9 9 0 1 1 9-9a9.01 9.01 0 0 1-9 9"/>',
    attributes: {
      width: '1em',
      height: '1em',
      viewBox: '0 0 32 32',
    },
  },
}
