import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'
import glob from 'fast-glob'
import { format } from 'prettier'
import { getIconData, iconToSVG } from '@iconify/utils'
import type { IconifyJSON } from '@iconify/types'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(import.meta.url)
const pickerSource = 'packages/components/icon-picker/src/icon-picker.ts'
const generatedFiles = new Set([
  'packages/components/icon/src/builtin-carbon-icons.ts',
  'packages/components/icon-picker/src/default-carbon-icons.ts',
])
const pattern = /cb:([a-z0-9-]+)/gi

const readNames = async (files: string[]) => {
  const names = new Set<string>()
  for (const file of files) {
    const source = await readFile(path.join(root, file), 'utf8')
    for (const match of source.matchAll(pattern)) names.add(match[1])
  }
  return [...names].sort()
}

const sourceFiles = (
  await glob('packages/components/*/src/**/*.{ts,vue}', { cwd: root })
).filter((file) => !generatedFiles.has(file.replace(/\\/g, '/')))
const essentialNames = await readNames(
  sourceFiles.filter((file) => file.replace(/\\/g, '/') !== pickerSource),
)
const pickerNames = await readNames([pickerSource])
const collection = JSON.parse(
  await readFile(require.resolve('@iconify-json/carbon/icons.json'), 'utf8'),
) as IconifyJSON

const renderRecord = (names: string[]) =>
  Object.fromEntries(
    names.map((name) => {
      const icon = getIconData(collection, name)
      if (!icon) throw new Error(`Missing Carbon icon: ${name}`)
      const rendered = iconToSVG(icon, { width: '1em', height: '1em' })
      return [name, { body: rendered.body, attributes: rendered.attributes }]
    }),
  )

const generatedModule = async (
  typeImport: string,
  exportName: string,
  names: string[],
) =>
  format(
    `${typeImport}

// Generated by scripts/generate-builtin-icon-fallbacks.ts. Do not edit manually.
export const ${exportName}: Record<string, SaxIconData> = ${JSON.stringify(
      renderRecord(names),
      null,
      2,
    )}
`,
    { parser: 'typescript', singleQuote: true, semi: false },
  )

await writeFile(
  path.join(root, 'packages/components/icon/src/builtin-carbon-icons.ts'),
  await generatedModule(
    "import type { SaxIconData } from './icon'",
    'builtinCarbonIcons',
    essentialNames,
  ),
  'utf8',
)
await writeFile(
  path.join(
    root,
    'packages/components/icon-picker/src/default-carbon-icons.ts',
  ),
  await generatedModule(
    "import type { SaxIconData } from '@vuesax-alpha/components/icon'",
    'defaultCarbonIcons',
    pickerNames,
  ),
  'utf8',
)

process.stdout.write(
  `Generated ${essentialNames.length} component fallbacks and ${pickerNames.length} IconPicker defaults.`,
)
