#!/usr/bin/env node
/**
 * Sync English docs to docs/zh/ with link rewrites and Chinese UI text.
 * New components (13) are generated by generate-new-component-docs.mjs.
 */
import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const docsDir = path.join(root, 'docs')
const zhDir = path.join(docsDir, 'zh')

const NEW_COMPONENTS = new Set([
  'divider', 'progress', 'chip', 'breadcrumb', 'textarea', 'collapse',
  'list', 'images', 'prompt', 'tabs', 'slider', 'upload', 'spacer',
])

const sectionTitleZh = {
  Default: '默认',
  Color: '颜色',
  Colors: '颜色',
  Text: '文本',
  Icons: '图标',
  Loading: '加载',
  Indeterminate: '不确定',
  Square: '方形',
  Example: '示例',
  API: 'API',
  Solid: '实心',
  Border: '边框',
  Shadow: '阴影',
  Gradient: '渐变',
  Relief: '浮雕',
  Animate: '动画',
  Icon: '图标',
  Title: '标题',
  'Hidden Content': '隐藏内容',
  Pagination: '分页',
  Footer: '页脚',
  'Progress Bar': '进度条',
  Closable: '可关闭',
  'Time Close': '定时关闭',
  Flat: '扁平',
  Transparent: '透明',
  Size: '尺寸',
  Block: '块级',
  Circle: '圆形',
  'Text Position': '文本位置',
  Background: '背景',
  Style: '样式',
  Height: '高度',
  Width: '宽度',
  Label: '标签',
  Counter: '计数器',
  Accordion: '手风琴',
  Type: '类型',
  'Open Hover': '悬停展开',
  'Icon Arrow': '箭头图标',
  Header: '标题行',
  Content: '内容',
  Avatar: '头像',
  Hover: '悬停',
  More: '更多',
  Alert: '警告',
  Alignments: '对齐',
  Position: '位置',
  Ticks: '刻度',
  'Text Fixed': '固定文本',
  Multiple: '多选',
  Automatic: '自动上传',
  Separator: '分隔符',
  Slot: '插槽',
  Alignment: '对齐',
  'Add and Remove Items': '增删条目',
  Prerequisites: '环境要求',
  Installation: '安装',
  'Register globally': '全局注册',
  'Dark / light theme': '深色 / 浅色主题',
  'On-demand components': '按需引入',
  'Try online first': '在线试用',
  'Documentation layout': '文档结构',
  'Basic usage pattern': '基本用法',
  'Configure with props': '通过属性配置',
  'Preview in Playground': '在 Playground 预览',
  'Design note': '设计说明',
  'Global registration': '全局注册',
  'Theme variables': '主题变量',
  'Per-component configuration': '单组件配置',
  'Auto-import (Vite)': '自动导入 (Vite)',
  Nuxt: 'Nuxt',
  'Interactive demos': '交互示例',
  'Local development': '本地开发',
  'How it maps to docs': '与文档的对应关系',
  'Design lineage': '设计渊源',
  Links: '链接',
  致敬: '致敬',
  'What is Sax Design Vue?': '什么是 Sax Design Vue？',
  'Quick links': '快速链接',
  'Design philosophy': '设计理念',
}

const pageDescriptionZh = {
  divider: '在文本或区块之间添加分割线，支持颜色、图标与多种布局。',
  progress: '展示确定或不确定的加载进度。',
  chip: '标签是表示输入、属性或操作的紧凑元素。',
  breadcrumb: '展示当前页面在导航层级中的位置。',
  textarea: '多行文本输入，支持标签、计数与尺寸配置。',
  collapse: '可展开/折叠的内容面板，多种视觉样式。',
  list: '结构化列表，支持标题、图标、头像与自定义插槽。',
  images: '响应式图片网格，支持悬停动效与布局选项。',
  prompt: '用于提醒与确认的模态提示框，可自定义操作。',
  tabs: '将内容组织为可切换的标签面板。',
  slider: '沿轨道拖动选择数值。',
  upload: '手动或自动上传文件，支持预览与数量限制。',
  spacer: 'Flex 间距工具，用于工具栏与操作行中推开元素。',
  switch: '开关组件，用于在两种状态之间切换。',
  alert: '用于向用户展示重要信息的提示框。',
  button: '按钮组件，支持多种样式与交互状态。',
  input: '文本输入框，支持标签、图标与校验状态。',
  checkbox: '复选框，用于多选场景。',
  select: '下拉选择器，支持单选与多选。',
  avatar: '头像组件，支持图片、文字与图标。',
  loading: '加载动画，用于异步操作反馈。',
  notification: '通知消息，从屏幕边缘弹出。',
  radio: '单选框，用于互斥选项。',
  tooltip: '工具提示，悬停时显示补充说明。',
  dialog: '对话框，用于模态交互。',
  pagination: '分页器，用于数据列表翻页。',
  table: '表格，用于展示结构化数据。',
  navbar: '顶部导航栏组件。',
  sidebar: '侧边栏导航组件。',
  card: '卡片容器，用于分组展示内容。',
  'time-select': '时间选择器组件。',
  scrollbar: '自定义滚动条。',
  rate: '评分组件。',
  badge: '徽章，用于数字或状态标记。',
}

function rewriteLinks(content) {
  return content
    .replace(/\]\(\/zh\//g, '](__ZH__')
    .replace(/\]\(\/(guide|components|theme|icons|layout)\//g, '](/zh/$1/')
    .replace(/\]\(\/(guide|components|theme|icons|layout)\)/g, '](/zh/$1/)')
    .replace(/\]\(__ZH__/g, '](/zh/')
}

function translateSectionHeaders(content) {
  return content.replace(/^## (.+)$/gm, (match, title) => {
    const clean = title.replace(/ <Badge[^>]*\/>/g, '').trim()
    const zh = sectionTitleZh[clean]
    if (!zh) return match
    const badge = title.includes('<Badge') ? title.slice(clean.length) : ''
    return `## ${zh}${badge}`
  })
}

function translatePageTitle(content, fileBase) {
  const titleMap = {
    README: 'Button',
    alert: 'Alert',
    loading: 'Loading',
    input: 'Input',
    checkbox: 'Checkbox',
    switch: 'Switch',
    select: 'Select',
    avatar: 'Avatar',
    notification: 'Notification',
    radio: 'Radio',
    tooltip: 'Tooltip',
    dialog: 'Dialog',
    pagination: 'Pagination',
    table: 'Table',
    navbar: 'Navbar',
    sidebar: 'Sidebar',
    card: 'Card',
    'time-select': 'Time select',
    scrollbar: 'Scrollbar',
    rate: 'Rate',
    badge: 'Badge',
    popper: 'Popper',
  }
  const name = fileBase === 'README' ? 'Button' : titleMap[fileBase] || fileBase
  return content.replace(/^# .+$/m, `# ${name}`)
}

function injectZhDescription(content, fileBase) {
  const desc = pageDescriptionZh[fileBase]
  if (!desc || content.includes('\ndescription:')) return content
  if (!content.startsWith('---')) return content
  const end = content.indexOf('\n---\n', 4)
  if (end < 0) return content
  const fm = content.slice(0, end)
  const body = content.slice(end)
  if (fm.includes('description:')) {
    return content.replace(
      /^description:.*$/m,
      `description: ${JSON.stringify(desc)}`
    )
  }
  return `${fm}\ndescription: ${JSON.stringify(desc)}${body}`
}

function syncMarkdownFile(relPath) {
  const src = path.join(docsDir, relPath)
  const dest = path.join(zhDir, relPath)
  if (!fs.existsSync(src)) return
  const fileBase = path.basename(relPath, '.md')
  const dirBase = path.basename(path.dirname(relPath))
  const key = dirBase === 'components' ? fileBase : fileBase

  let content = fs.readFileSync(src, 'utf8')
  content = rewriteLinks(content)
  content = translateSectionHeaders(content)
  if (dirBase === 'components') {
    content = translatePageTitle(content, fileBase)
    content = injectZhDescription(content, key === 'README' ? 'button' : key)
  }
  fs.mkdirSync(path.dirname(dest), { recursive: true })
  fs.writeFileSync(dest, content)
}

function writeZhGuides() {
  const guides = {
    'README.md': `---
home: true
heroText: Sax Design Vue
description: 现代化 Vue 3 组件库 — 实用指南、组件配置与在线 Playground。
action:
  text: 快速开始
  link: /zh/guide/getting-started/
---
`,
    'guide/README.md': `# 介绍

<card>

## 什么是 Sax Design Vue？

Sax Design Vue 是从 Vuesax 生态迁移而来的 **Vue 3 + TypeScript** 组件库。面向现代工具链（Vite、pnpm workspaces），聚焦开发者最需要的三件事：

1. **如何使用**组件构建真实项目
2. **如何配置**属性、插槽与主题
3. **如何预览**行为 — 使用[在线 Playground](/zh/guide/playground)

</card>

<card>

## 快速链接

- [快速开始](/zh/guide/getting-started/) — 安装、注册、暗色模式
- [使用组件](/zh/guide/using-components) — 示例、属性、Playground 工作流
- [配置](/zh/guide/configuration) — 主题、自动导入、全局设置
- [Playground](/zh/guide/playground) — 浏览器内交互示例

</card>

<card>

## 设计理念

与原版 Vuesax 一样，我们避免千篇一律的 Material 风格。组件在视觉上保持表现力，同时通过属性与 CSS 变量（含**浅色 / 深色**主题）易于配置。

</card>
`,
    'guide/getting-started.md': `# 快速开始

<card>

## 环境要求

Sax Design Vue 面向 **Vue 3.3+**，推荐使用现代打包工具（Vite）。请先安装 Vue，再添加组件库。

</card>

<card>

## 安装

<command>

<template #pnpm>

\`\`\`bash
pnpm add vue vuesax-alpha
\`\`\`

</template>

<template #npm>

\`\`\`bash
npm install vue vuesax-alpha
\`\`\`

</template>

<template #yarn>

\`\`\`bash
yarn add vue vuesax-alpha
\`\`\`

</template>

</command>

</card>

<card>

## 全局注册

<command>

\`\`\`ts
import { createApp } from 'vue'
import Vuesax from 'vuesax-alpha'
import App from './App.vue'

import 'vuesax-alpha/theme-chalk/index.css'
import 'vuesax-alpha/theme-chalk/dark/css-vars.css'

createApp(App).use(Vuesax).mount('#app')
\`\`\`

</command>

即使从浅色模式开始，也建议引入暗色 CSS 变量文件，以支持运行时主题切换。

</card>

<card>

## 深色 / 浅色主题

切换 \`html\` 元素的 \`dark\` 类（本站通过导航栏开关使用相同方式）：

<command>

\`\`\`ts
document.documentElement.classList.toggle('dark')
\`\`\`

</command>

或使用 \`@vueuse/core\`：

<command>

\`\`\`ts
import { useDark, useToggle } from '@vueuse/core'

const isDark = useDark()
const toggleDark = useToggle(isDark)
\`\`\`

</command>

</card>

<card>

## 按需引入

<command>

\`\`\`ts
import { createApp } from 'vue'
import { SAlert, SButton } from 'vuesax-alpha'
import App from './App.vue'

import 'vuesax-alpha/theme-chalk/index.css'
import 'vuesax-alpha/theme-chalk/dark/css-vars.css'

createApp(App).use(SAlert).use(SButton).mount('#app')
\`\`\`

</command>

自动导入配置见[使用组件](/zh/guide/using-components)。

</card>

<card>

## 在线试用

在集成到项目前，可先打开 [Playground](/zh/guide/playground) 预览组件。

</card>
`,
    'guide/using-components.md': `# 使用组件

<card>

## 文档结构

每个组件页遵循相同结构：

1. **实时示例** — 与应用中相同的 API 渲染
2. **代码标签** — 可复制的 template / script / style 片段
3. **API 表** — 由 frontmatter 生成的属性、事件、插槽与暴露项

新迁移的组件在侧栏带有绿色 **New** 标记。

</card>

<card>

## 基本用法

<command>

\`\`\`vue
<template>
  <vs-button color="primary" type="flat">Save</vs-button>
</template>
\`\`\`

</command>

在入口文件中引入样式一次（见[快速开始](/zh/guide/getting-started/)）。

</card>

<card>

## 通过属性配置

多数视觉变化通过属性驱动，无需额外 CSS：

<command>

\`\`\`vue
<vs-alert color="success" closable v-model="open">
  Saved successfully.
</vs-alert>
\`\`\`

</command>

打开组件文档，在 API 区找到对应属性，并使用链接示例锚点（如 \`#color\`）。

</card>

<card>

## 在 Playground 预览

集成到仓库前，打开 [Playground](/zh/guide/playground) 选择组件示例。Playground 与本站使用相同的工作区构建。

</card>

<card>

## 设计说明

视觉语言继承自 [Vuesax](https://github.com/lusaxweb/vuesax)。Sax Design Vue 在面向 Vue 3 工具链与现代文档工作流的同时，保留富有表现力的外观。

</card>
`,
    'guide/configuration.md': `# 配置

<card>

## 全局注册

在应用启动时注册完整库：

<command>

\`\`\`ts
import Vuesax from 'vuesax-alpha'

app.use(Vuesax)
\`\`\`

</command>

若需 tree-shaking，仅注册需要的组件 — 见[使用组件](/zh/guide/using-components)。

</card>

<card>

## 主题变量

Vuesax 组件读取 \`--vs-primary\` 等 CSS 变量。可在 \`:root\` 或 \`html.dark\` 上覆盖：

<command>

\`\`\`css
:root {
  --vs-primary: 37, 99, 255;
}

html.dark {
  --vs-primary: 96, 165, 250;
}
\`\`\`

</command>

本站使用相同变量系统 — 可用导航栏主题开关预览暗色模式。

</card>

<card>

## 单组件配置

每个组件页文档包含：

- **Props** — 类型化配置（颜色、尺寸、变体）
- **Events** — \`v-model\` 与交互回调
- **Slots** — 组合与自定义内容
- **示例 + 代码** — 实时预览与可复制片段

从默认示例开始，再跳转到页面底部的 API 表。

</card>

<card>

## 自动导入 (Vite)

使用 \`unplugin-vue-components\` 与官方 resolver：

<command>

\`\`\`ts
import Components from 'unplugin-vue-components/vite'
import { VuesaxAlphaResolver } from '@vuesax-alpha/auto-import-resolver'

export default defineConfig({
  plugins: [
    Components({
      resolvers: [VuesaxAlphaResolver({ importStyle: 'sass' })],
    }),
  ],
})
\`\`\`

</command>

</card>

<card>

## Nuxt

SSR 相关说明见 [Nuxt 集成](/zh/guide/nuxt/)。

</card>
`,
    'guide/playground.md': `# Playground

<card>

## 交互示例

左侧浏览组件源码，右侧查看实时预览。可复制片段，或打开完整 Playground 获得分屏代码 + 预览体验。

<PlaygroundEmbed />

</card>

<card>

## 本地开发

克隆仓库并本地运行 play 应用：

<command>

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

</command>

然后访问 hash 路由，如 \`#/divider\`、\`#/tabs\` 或 \`#/upload\` 打开单个示例。

</card>

<card>

## 与文档的对应关系

每个组件页都包含可复制的示例代码。Playground 使用相同组件 API — 从这里选择示例，粘贴到项目中，再按组件页 **API** 区调整属性。

</card>
`,
  }

  for (const [rel, content] of Object.entries(guides)) {
    const dest = path.join(zhDir, rel)
    fs.mkdirSync(path.dirname(dest), { recursive: true })
    fs.writeFileSync(dest, content)
  }

  // Sync nuxt + migration from en with link rewrite
  for (const file of ['guide/nuxt.md', 'guide/migration.md', 'theme/README.md', 'theme/font.md', 'theme/icons.md', 'theme/generate.md', 'icons/README.md', 'layout/README.md']) {
    syncMarkdownFile(file)
  }
}

function walkMarkdown(dir, base = '') {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  for (const entry of entries) {
    const rel = path.join(base, entry.name)
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'zh' || entry.name === '.vuepress') continue
      walkMarkdown(full, rel)
    } else if (entry.name.endsWith('.md')) {
      const key = rel.replace(/\\/g, '/')
      if (key.startsWith('guide/') && [
        'guide/README.md', 'guide/getting-started.md', 'guide/using-components.md',
        'guide/configuration.md', 'guide/playground.md',
      ].includes(key)) continue
      if (key === 'README.md') continue
      if (key.startsWith('components/')) {
        const comp = path.basename(key, '.md')
        if (NEW_COMPONENTS.has(comp)) continue
      }
      syncMarkdownFile(key)
    }
  }
}

writeZhGuides()
walkMarkdown(docsDir)
console.log('Synced zh docs to docs/zh/')
