export const PKG_PREFIX = '@vuesax-alpha'
export const PKG_NAME = 'sax-design-vue'
export const PKG_CAMELCASE_NAME = 'SaxDesignVue'
export const PKG_CAMELCASE_LOCAL_NAME = 'SaxDesignVueLocale'
export const PKG_BRAND_NAME = 'Sax Design Vue'
